services:

  #  databases
  sandbox-db:
    container_name: sandbox-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/sandbox-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #backends

  #frontends

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.nginx/compose/nginx-dev-e2e.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
